import { Box, Section, Text } from "@/presentation/components"
import { BaseLayout, Footer } from "@/presentation/layouts"
import Head from "next/head"

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <BaseLayout>
                    <Section title="контакты">
                        <Text.Description>
                            Hello, i’m Traximullin!

                            I can develop responsive websites from scratch and raise them into modern 
                            user-friendly web experiences. 

                            Transforming my creativity and knowledge into a websites has been my passion
                            for over a year. I have been helping various clients to establish their presence online.
                            I always strive to learn about the newest technologies and frameworks.
                        </Text.Description>
                        <Box>
                            1
                        </Box>
                    </Section>
                </BaseLayout>
                <Footer />
            </main>
        </>
    )
}
